version: '3.9'

services:
  db:
    image: postgres:15-alpine
    # restart: unless-stopped
    expose:
      - 5432 # port for other containers, default
    ports:
      - 5432:5432 # port for connecting outside docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DN: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
