test:
  adapter: postgresql
  username: postgres
  database: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000
  prepared_statements: <%= ENV.fetch('PREPARED_STATEMENTS', '1') == '1' %>
